### ISSUE TITLE
Can't print any document

### ISSUE THREAD

**Issue by hophamlam** [minhng92/odoo-16-docker-compose#5]
![image](https://user-images.githubusercontent.com/53455661/223373467-67d9c59a-6c54-4e51-bcb4-1be64cc8da08.png)
![image](https://user-images.githubusercontent.com/53455661/223373528-71d223e5-daf1-48ce-866a-f073fb372555.png)
![image](https://user-images.githubusercontent.com/53455661/223374204-757960b7-e0dd-49a7-ba56-82e9097d7cf0.png)

I don't know if this happens only to me 😟 when you try to print any document (quotation, sales order, purchase order,...) it keeps spinning and nothing happens. If you refresh the page, it still responds properly. I have tried all of your odoo repo (from 13 to 16) and the same things happens (or maybe I have done something wrongly because that task is pretty basic, I've used your 1-command script install).

Hope you doing well!

**Comment by minhng92** [comment]
Hi @hophamlam ,

I tried to reproduce the issue using a one-command script on my machines, but I had no luck. The first time I downloaded the PDF document, it took some time to start the download. Please be patient.

I'm not sure that configuring the system parameters will fix your issue, but you should give it a try by adding report.url = http://127.0.0.1:8069/.

![image](https://user-images.githubusercontent.com/34470011/223482826-27e1b817-a4fe-421d-9311-0c5eaf851947.png)

**Comment by hophamlam** [comment]
Sorry for late feedback, too busy last 2 weeks 😟😟 
Adding report.url (your remote server url in case you are deploying, I run into this issue at a test Ubuntu server) will fix this
Thanks for quick response (but mine is not 🤣🤣), you amazing!
