### ISSUE TITLE
for activation custom addons

### ISSUE THREAD

**Issue by Khant-Nyar** [minhng92/odoo-16-docker-compose#9]
I want to do like 
python3 odoo-bin --addons-path=/Users/khantnyar/Downloads/odoo/odoo/addons -d odoo16db -i base -c odoo.conf

everything is fine with your compose but I want to add -I base how can I do this ?

**Comment by minhng92** [comment]
Hi @Khant-Nyar ,

The docker container executes odoo-bin with no params by default. You can add your custom params to the **command** in docker-compose.yml at line:
https://github.com/minhng92/odoo-16-docker-compose/blob/c28f67b805413b7ebe7c8c4a91c1db38b67e2f83/docker-compose.yml#L23C1-L23C1

It will look something like this:
```
command: -- --without-demo=all --database=test --init=point_of_sale --update=point_of_sale

or in your case:
command: -- -d odoo16db -i base
```

**Comment by Khant-Nyar** [comment]
Thanks man I got it
